import React, { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { AuthGuard } from "@/components/AuthGuard";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { FileText, Download, Eye } from "lucide-react";
import { useNavigate } from "react-router-dom";

interface Payslip {
  id: string;
  invoice_number: string;
  invoice_date: string;
  period_start: string;
  period_end: string;
  operator_id: string;
  gross_pay: number;
  deductions: number;
  net_pay: number;
  generated_at: string;
}

const DriverPayslips = () => {
  const navigate = useNavigate();
  const { toast } = useToast();
  const [payslips, setPayslips] = useState<Payslip[]>([]);
  const [loading, setLoading] = useState(true);
  const [driverId, setDriverId] = useState<string | null>(null);

  useEffect(() => {
    loadDriverId();
  }, []);

  useEffect(() => {
    if (driverId) {
      loadPayslips();
    }
  }, [driverId]);

  const loadDriverId = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      const { data: driver, error } = await supabase
        .from("drivers")
        .select("id")
        .eq("user_id", user.id)
        .single();

      if (error) throw error;
      setDriverId(driver?.id || null);
    } catch (error: any) {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    }
  };

  const loadPayslips = async () => {
    if (!driverId) return;

    try {
      const { data, error } = await supabase
        .from("payslips")
        .select("*")
        .eq("driver_id", driverId)
        .order("invoice_date", { ascending: false });

      if (error) throw error;
      setPayslips(data || []);
    } catch (error: any) {
      toast({
        title: "Error loading payslips",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleViewPayslip = (payslipId: string) => {
    navigate(`/payslips/${payslipId}`);
  };

  return (
    <AuthGuard allowedRoles={["driver"]}>
      <div className="min-h-screen bg-background p-6">
      <div className="max-w-7xl mx-auto space-y-6">
        <div>
          <h1 className="text-3xl font-bold">My Payslips</h1>
          <p className="text-muted-foreground mt-1">
            View and download your payslips
          </p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Payslips</CardTitle>
            <CardDescription>
              Your payslip history
            </CardDescription>
          </CardHeader>
          <CardContent>
            {loading ? (
              <p className="text-muted-foreground">Loading...</p>
            ) : payslips.length === 0 ? (
              <div className="text-center py-8">
                <FileText className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
                <p className="text-muted-foreground">No payslips found</p>
                <p className="text-sm text-muted-foreground mt-2">
                  Payslips will appear here once they are generated by Finance
                </p>
              </div>
            ) : (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Invoice Number</TableHead>
                    <TableHead>Period</TableHead>
                    <TableHead>Operator ID</TableHead>
                    <TableHead>Gross Pay</TableHead>
                    <TableHead>Deductions</TableHead>
                    <TableHead>Net Pay</TableHead>
                    <TableHead>Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {payslips.map((payslip) => (
                    <TableRow key={payslip.id}>
                      <TableCell className="font-medium">
                        {payslip.invoice_number}
                      </TableCell>
                      <TableCell>
                        {new Date(payslip.period_start).toLocaleDateString()} -{" "}
                        {new Date(payslip.period_end).toLocaleDateString()}
                      </TableCell>
                      <TableCell>{payslip.operator_id}</TableCell>
                      <TableCell>£{payslip.gross_pay.toFixed(2)}</TableCell>
                      <TableCell>£{payslip.deductions.toFixed(2)}</TableCell>
                      <TableCell className="font-semibold">
                        £{payslip.net_pay.toFixed(2)}
                      </TableCell>
                      <TableCell>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => handleViewPayslip(payslip.id)}
                        >
                          <Eye className="w-4 h-4 mr-2" />
                          View
                        </Button>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
    </AuthGuard>
  );
};

export default DriverPayslips;
